GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Title Here",
    "author": "Author Here",
    "url": "www.google.com",
    "userId": "placeholder",
    "likes": "352"
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "asmith",
    "name": "Alex Smith",
    "password": "pass123"
}