GET http://localhost:3003/api/blogs

###

GET http://localhost:3003/api/users

###

POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "jsmith",
    "password": "pass123"
}

###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpzbWl0aCIsImlkIjoiNjZlNzEzOWQ4ZDM5MWMxOWZmYmY4MTZhIiwiaWF0IjoxNzI2NjgwMTE4fQ.r24ouyBCQu01wMHku7dxeMzcWg5EB1XOyKChz1E6XMs

{
    "title": "Title Here",
    "author": "Author Here",
    "url": "www.google.com",
    "userId": "66e7139d8d391c19ffbf816a",
    "likes": "352"
}

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "jsmith",
    "name": "John Smith",
    "password": "pass123"
}